import { WineForAnalysisResponse } from './types'

export const mockWineForAnalysisResponse: WineForAnalysisResponse = {
  rows: [
    {
      id: '1',
      name: 'Château Margaux',
      vintage: 2015,
      wintage: 2015,
      grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
      capacityName: 'Standard Bottle',
      typeName: 'Red Wine',
      color: {
        id: 'red',
        colorHex: '#722F37',
        name: 'Red',
      },
      image: {
        name: 'chateau-margaux-2015.jpg',
        originalName: 'Chateau_Margaux_2015_original.jpg',
        mimetype: 'image/jpeg',
        size: 2048576,
        smallUrl: 'https://example.com/images/small/chateau-margaux-2015.jpg',
        mediumUrl: 'https://example.com/images/medium/chateau-margaux-2015.jpg',
        originalUrl: 'https://example.com/images/original/chateau-margaux-2015.jpg',
      },
    },
    {
      id: '2',
      name: 'Dom Pérignon',
      vintage: 2012,
      wintage: 2012,
      grapeVariety: 'Chardonnay, Pinot Noir',
      capacityName: 'Magnum',
      typeName: 'Sparkling Wine',
      color: {
        id: 'yellow',
        colorHex: '#FFD700',
        name: 'Yellow',
      },
      image: {
        name: 'dom-perignon-2012.jpg',
        originalName: 'Dom_Perignon_2012_original.jpg',
        mimetype: 'image/jpeg',
        size: 1859328,
        smallUrl: 'https://example.com/images/small/dom-perignon-2012.jpg',
        mediumUrl: 'https://example.com/images/medium/dom-perignon-2012.jpg',
        originalUrl: 'https://example.com/images/original/dom-perignon-2012.jpg',
      },
    },
    {
      id: '3',
      name: 'Sancerre Blanc',
      vintage: 2021,
      wintage: 2021,
      grapeVariety: 'Sauvignon Blanc',
      capacityName: 'Standard Bottle',
      typeName: 'White Wine',
      color: {
        id: 'white',
        colorHex: '#F5F5DC',
        name: 'White',
      },
      image: {
        name: 'sancerre-blanc-2021.jpg',
        originalName: 'Sancerre_Blanc_2021_original.jpg',
        mimetype: 'image/jpeg',
        size: 1572864,
        smallUrl: 'https://example.com/images/small/sancerre-blanc-2021.jpg',
        mediumUrl: 'https://example.com/images/medium/sancerre-blanc-2021.jpg',
        originalUrl: 'https://example.com/images/original/sancerre-blanc-2021.jpg',
      },
    },
    {
      id: '4',
      name: "Rosé d'Anjou",
      vintage: 2022,
      wintage: 2022,
      grapeVariety: 'Grolleau, Gamay',
      capacityName: 'Standard Bottle',
      typeName: 'Rosé Wine',
      color: {
        id: 'pink',
        colorHex: '#FFC0CB',
        name: 'Pink',
      },
      image: {
        name: 'rose-anjou-2022.jpg',
        originalName: 'Rose_Anjou_2022_original.jpg',
        mimetype: 'image/jpeg',
        size: 1782579,
        smallUrl: 'https://example.com/images/small/rose-anjou-2022.jpg',
        mediumUrl: 'https://example.com/images/medium/rose-anjou-2022.jpg',
        originalUrl: 'https://example.com/images/original/rose-anjou-2022.jpg',
      },
    },
    {
      id: '5',
      name: 'Barolo',
      vintage: 2018,
      wintage: 2018,
      grapeVariety: 'Nebbiolo',
      capacityName: 'Standard Bottle',
      typeName: 'Red Wine',
      color: {
        id: 'red',
        colorHex: '#8B0000',
        name: 'Red',
      },
      image: {
        name: 'barolo-2018.jpg',
        originalName: 'Barolo_2018_original.jpg',
        mimetype: 'image/jpeg',
        size: 2097152,
        smallUrl: 'https://example.com/images/small/barolo-2018.jpg',
        mediumUrl: 'https://example.com/images/medium/barolo-2018.jpg',
        originalUrl: 'https://example.com/images/original/barolo-2018.jpg',
      },
    },
  ],
  totalPages: 2,
  count: 8,
}
