import { mockColors } from '../../wine-types/entities/mock'
import { WineAromaGroup } from './types/flavor-types'

export const mockAromaGroups: WineAromaGroup[] = [
  {
    id: '1',
    nameUa: 'Фруктові аромати',
    nameEn: 'Fruit Aromas',
    colorHex: '#FF6B6B',
    sortNumber: 1,
    subgroups: [
      {
        id: '1-1',
        nameUa: 'Цитрусові',
        nameEn: 'Citrus',
        sortNumber: 1,
        aromas: [
          {
            id: '1-1-1',
            nameUa: 'Лимон',
            nameEn: 'Lemon',
            colorHex: '#FFE785',
            sortNumber: 1,
          },
          {
            id: '1-1-2',
            nameUa: 'Апельсин',
            nameEn: 'Orange',
            colorHex: '#FFE785',
            sortNumber: 2,
          },
          {
            id: '1-1-3',
            nameUa: 'Грейпфрут',
            nameEn: 'Grapefruit',
            colorHex: '#FFE785',
            sortNumber: 3,
          },
        ],
      },
      {
        id: '1-2',
        nameUa: 'Ягідні',
        nameEn: 'Berry',
        sortNumber: 2,
        aromas: [
          {
            id: '1-2-1',
            nameUa: 'Полуниця',
            nameEn: 'Strawberry',
            colorHex: '#F075B3',
            sortNumber: 1,
          },
          {
            id: '1-2-2',
            nameUa: 'Малина',
            nameEn: 'Raspberry',
            colorHex: '#F075B3',
            sortNumber: 2,
          },
          {
            id: '1-2-3',
            nameUa: 'Чорниця',
            nameEn: 'Blueberry',
            colorHex: '#F075B3',
            sortNumber: 3,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '2',
    nameUa: 'Ягідні аромати',
    nameEn: 'Berry Aromas',
    colorHex: '#E84393',
    sortNumber: 2,
    subgroups: [
      {
        id: '2-1',
        nameUa: 'Лісові ягоди',
        nameEn: 'Forest Berries',
        sortNumber: 1,
        aromas: [
          {
            id: '2-1-1',
            nameUa: 'Суниця',
            nameEn: 'Wild Strawberry',
            colorHex: '#F075B3',
            sortNumber: 1,
          },
          {
            id: '2-1-2',
            nameUa: 'Чорна смородина',
            nameEn: 'Blackcurrant',
            colorHex: '#F075B3',
            sortNumber: 2,
          },
          {
            id: '2-1-3',
            nameUa: 'Журавлина',
            nameEn: 'Cranberry',
            colorHex: '#F075B3',
            sortNumber: 3,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '3',
    nameUa: 'Цитрусові аромати',
    nameEn: 'Citrus Aromas',
    colorHex: '#FFD93D',
    sortNumber: 3,
    subgroups: [
      {
        id: '3-1',
        nameUa: 'Цитрусові',
        nameEn: 'Citrus',
        sortNumber: 1,
        aromas: [
          {
            id: '3-1-1',
            nameUa: 'Лимон',
            nameEn: 'Lemon',
            colorHex: '#FFE785',
            sortNumber: 1,
          },
          {
            id: '3-1-2',
            nameUa: 'Лайм',
            nameEn: 'Lime',
            colorHex: '#FFE785',
            sortNumber: 2,
          },
          {
            id: '3-1-3',
            nameUa: 'Грейпфрут',
            nameEn: 'Grapefruit',
            colorHex: '#FFE785',
            sortNumber: 3,
          },
          {
            id: '3-1-4',
            nameUa: 'Помело',
            nameEn: 'Pomelo',
            colorHex: '#FFE785',
            sortNumber: 4,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '4',
    nameUa: 'Квіткові аромати',
    nameEn: 'Floral Aromas',
    colorHex: '#A29BFE',
    sortNumber: 4,
    subgroups: [
      {
        id: '4-1',
        nameUa: 'Квіти',
        nameEn: 'Flowers',
        sortNumber: 1,
        aromas: [
          {
            id: '4-1-1',
            nameUa: 'Троянда',
            nameEn: 'Rose',
            colorHex: '#C7C3FF',
            sortNumber: 1,
          },
          {
            id: '4-1-2',
            nameUa: 'Жасмин',
            nameEn: 'Jasmine',
            colorHex: '#C7C3FF',
            sortNumber: 2,
          },
          {
            id: '4-1-3',
            nameUa: 'Бузок',
            nameEn: 'Lilac',
            colorHex: '#C7C3FF',
            sortNumber: 3,
          },
          {
            id: '4-1-4',
            nameUa: 'Фіалка',
            nameEn: 'Violet',
            colorHex: '#C7C3FF',
            sortNumber: 4,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '5',
    nameUa: 'Пряні аромати',
    nameEn: 'Spicy Aromas',
    colorHex: '#6BCF7F',
    sortNumber: 5,
    subgroups: [
      {
        id: '5-1',
        nameUa: 'Прянощі',
        nameEn: 'Spices',
        sortNumber: 1,
        aromas: [
          {
            id: '5-1-1',
            nameUa: 'Ваніль',
            nameEn: 'Vanilla',
            colorHex: '#9DDFAB',
            sortNumber: 1,
          },
          {
            id: '5-1-2',
            nameUa: 'Кориця',
            nameEn: 'Cinnamon',
            colorHex: '#9DDFAB',
            sortNumber: 2,
          },
          {
            id: '5-1-3',
            nameUa: 'Перець',
            nameEn: 'Pepper',
            colorHex: '#9DDFAB',
            sortNumber: 3,
          },
          {
            id: '5-1-4',
            nameUa: 'Гвоздика',
            nameEn: 'Clove',
            colorHex: '#9DDFAB',
            sortNumber: 4,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '6',
    nameUa: 'Горіхові аромати',
    nameEn: 'Nutty Aromas',
    colorHex: '#8B4513',
    sortNumber: 6,
    subgroups: [
      {
        id: '6-1',
        nameUa: 'Горіхи',
        nameEn: 'Nuts',
        sortNumber: 1,
        aromas: [
          {
            id: '6-1-1',
            nameUa: 'Мигдаль',
            nameEn: 'Almond',
            colorHex: '#B57945',
            sortNumber: 1,
          },
          {
            id: '6-1-2',
            nameUa: 'Фундук',
            nameEn: 'Hazelnut',
            colorHex: '#B57945',
            sortNumber: 2,
          },
          {
            id: '6-1-3',
            nameUa: 'Горіх',
            nameEn: 'Walnut',
            colorHex: '#B57945',
            sortNumber: 3,
          },
          {
            id: '6-1-4',
            nameUa: 'Кешью',
            nameEn: 'Cashew',
            colorHex: '#B57945',
            sortNumber: 4,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '7',
    nameUa: 'Деревні аромати',
    nameEn: 'Woody Aromas',
    colorHex: '#CD6133',
    sortNumber: 7,
    subgroups: [
      {
        id: '7-1',
        nameUa: 'Деревина',
        nameEn: 'Wood',
        sortNumber: 1,
        aromas: [
          {
            id: '7-1-1',
            nameUa: 'Дуб',
            nameEn: 'Oak',
            colorHex: '#DE8B65',
            sortNumber: 1,
          },
          {
            id: '7-1-2',
            nameUa: 'Кедр',
            nameEn: 'Cedar',
            colorHex: '#DE8B65',
            sortNumber: 2,
          },
          {
            id: '7-1-3',
            nameUa: 'Смола',
            nameEn: 'Resin',
            colorHex: '#DE8B65',
            sortNumber: 3,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '8',
    nameUa: 'Земляні аромати',
    nameEn: 'Earthy Aromas',
    colorHex: '#795548',
    sortNumber: 8,
    subgroups: [
      {
        id: '8-1',
        nameUa: 'Гриби',
        nameEn: 'Mushrooms',
        sortNumber: 1,
        aromas: [
          {
            id: '8-1-1',
            nameUa: 'Трюфель',
            nameEn: 'Truffle',
            colorHex: '#9E7A6B',
            sortNumber: 1,
          },
          {
            id: '8-1-2',
            nameUa: 'Печериці',
            nameEn: 'Champignon',
            colorHex: '#9E7A6B',
            sortNumber: 2,
          },
          {
            id: '8-1-3',
            nameUa: 'Боровики',
            nameEn: 'Porcini',
            colorHex: '#9E7A6B',
            sortNumber: 3,
          },
        ],
      },
    ],
    colors: mockColors,
  },
  {
    id: '9',
    nameUa: 'Фруктові',
    nameEn: 'Fruity',
    colorHex: '#FF6B6B',
    sortNumber: 9,
    subgroups: [],
    colors: mockColors, // группа без подгрупп
  },
  {
    id: '10',
    nameUa: 'Квіткові',
    nameEn: 'Floral',
    colorHex: '#A29BFE',
    sortNumber: 10,
    subgroups: [],
    colors: mockColors, // группа без подгрупп
  },
  {
    id: '11',
    nameUa: 'Пряні',
    nameEn: 'Spicy',
    colorHex: '#6BCF7F',
    sortNumber: 11,
    subgroups: [],
    colors: mockColors, // группа без подгрупп
  },
  {
    id: '12',
    nameUa: 'Деревні',
    nameEn: 'Woody',
    colorHex: '#CD6133',
    sortNumber: 12,
    subgroups: [],
    colors: mockColors, // группа без подгрупп
  },
]

export const mockAromaItems = [
  {
    id: '1-1-1',
    nameUa: 'Лимон',
    nameEn: 'Lemon',
    colorHex: '#FFE785',
    sortNumber: 1,
  },
  {
    id: '1-1-2',
    nameUa: 'Апельсин',
    nameEn: 'Orange',
    colorHex: '#FFE785',
    sortNumber: 2,
  },
  {
    id: '4-1-1',
    nameUa: 'Троянда',
    nameEn: 'Rose',
    colorHex: '#C7C3FF',
    sortNumber: 1,
  },
  {
    id: '5-1-1',
    nameUa: 'Ваніль',
    nameEn: 'Vanilla',
    colorHex: '#9DDFAB',
    sortNumber: 1,
  },
]
