import { MapEvent } from "../../events/entities/types";

export const mockEvents:MapEvent[] = [
  {
    id: 1,
    userId: 1,
    theme: 'Natural Wine & Pet-Nats',
    restaurantName: 'Catch',
    locationLabel: 'Ukraine, Kyiv Reg, Irpin',
    latitude: 50.4501,
    longitude: 30.5234,
    countryId: 1,
    eventDate: '2025-08-14',
    eventTime: '14:30',
    price: 5700,
    currency: 'UAH',
    speakerName: 'Ihor Postoiankin',
    language: 'UA',
    seats: 1,
    phoneNumber: '+380501234567',
    tastingType: 'wine_set',
    repeatRule: 'never',
    isActive: true,
    isOnline: false,
    wineSet: [1, 5, 6],
  },
  {
    id: 2,
    userId: 1,
    theme: 'Порівняння Франція vs Італія',
    restaurantName: 'Wine House',
    locationLabel: 'Ukraine, Kyiv, Shevchenka 12',
    latitude: 50.4541,
    longitude: 30.5274,
    countryId: 1,
    eventDate: '2025-08-15',
    eventTime: '18:00',
    price: 4500,
    currency: 'UAH',
    speakerName: 'Olena Kovalenko',
    language: 'UA',
    seats: 2,
    phoneNumber: '+380501234568',
    tastingType: 'comparative',
    repeatRule: 'never',
    isActive: true,
    isOnline: false,
    wineSet: [2, 3, 7],
  },
]
