import { MapEvent } from '../../entities/types'

export const mockList: MapEvent[] = [
  {
    id: 1,
    theme: 'Natural Wine & Pet-Nats',
    restaurantName: 'Catch',
    locationLabel: 'Ukraine, Kyiv Reg, Irpin',
    latitude: 50.4501,
    longitude: 30.5234,
    eventDate: '2025-08-14',
    eventTime: '14:30',
    price: 5700,
    currency: 'UAH',
    speakerName: 'Ihor Postoiankin',
    language: 'UA',
    seats: 24,
    tastingType: 'wine_set',
    distanceKm: 0,
    isCanceled: false,
  },
  {
    id: 2,
    theme: 'Порівняння Франція vs Італія',
    restaurantName: 'Wine House',
    locationLabel: 'Ukraine, Kyiv, Shevchenka 12',
    latitude: 50.4541,
    longitude: 30.5274,
    eventDate: '2025-08-15',
    eventTime: '18:00',
    price: 4500,
    currency: 'UAH',
    speakerName: 'Olena Kovalenko',
    language: 'UA',
    seats: 20,
    tastingType: 'comparative',
    distanceKm: 0,
    isCanceled: false,
  },
  {
    id: 3,
    theme: 'Сліпа дегустація',
    restaurantName: 'Wine Bureau',
    locationLabel: 'Ukraine, Kyiv, Khreshchatyk 25',
    latitude: 50.448,
    longitude: 30.52,
    eventDate: '2025-08-16',
    eventTime: '19:30',
    price: 3200,
    currency: 'UAH',
    speakerName: 'Andriy Shevchenko',
    language: 'UA',
    seats: 16,
    tastingType: 'blind',
    distanceKm: 0,
    isCanceled: false,
  },
]
