import { IUserTable, USER_CATEGORIES } from "./IUser"



 const mockUsers: IUserTable[] = 
 [
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
  {
    id: '1',
    image: null,
    firstName: 'John',
    lastName: 'Doe',
    phoneNumber: '+1234567890',
    country: 'USA',
    birthday: '1990-05-15',
    email: 'john.doe@example.com',
    category: USER_CATEGORIES.WINE_LOVER,
  },
  {
    id: '2',
    image: null,
    firstName: 'Jane',
    lastName: 'Smith', 
    phoneNumber: '+0987654321',
    country: 'France',
    birthday: '1985-08-22',
    email: 'jane.smith@example.com',
    category: USER_CATEGORIES.WINE_EXPERT,
  },
]

export const MOCK_USERS = {
    rows: mockUsers,
    count: 2
}