import { WineColorGroup } from './types/color-types'

export const mockColorGroups: WineColorGroup[] = [
  {
    id: '1',
    nameUa: 'Червоний',
    nameEn: 'Red',
    colorHex: '#8B0000',
    shades: [
      {
        id: '1-1',
        nameUa: 'Бордовий',
        nameEn: 'Burgundy',
        tonePale: '#FFB6C1',
        toneMedium: '#DC143C',
        toneDeep: '#8B0000',
        colorHex: '#8B0000',
        sortNumber: 1,
      },
      {
        id: '1-2',
        nameUa: 'Рубіновий',
        nameEn: 'Ruby',
        tonePale: '#FF69B4',
        toneMedium: '#FF1493',
        toneDeep: '#C71585',
        colorHex: '#C71585',
        sortNumber: 2,
      },
      {
        id: '1-3',
        nameUa: 'Пурпурний',
        nameEn: 'Purple',
        tonePale: '#DDA0DD',
        toneMedium: '#BA55D3',
        toneDeep: '#800080',
        colorHex: '#800080',
        sortNumber: 3,
      },
    ],
  },
  {
    id: '2',
    nameUa: 'Білий',
    nameEn: 'White',
    colorHex: '#F5F5DC',
    shades: [
      {
        id: '2-1',
        nameUa: "Солом'яний",
        nameEn: 'Straw',
        tonePale: '#FFF8DC',
        toneMedium: '#F5DEB3',
        toneDeep: '#D2B48C',
        colorHex: '#F5DEB3',
        sortNumber: 1,
      },
      {
        id: '2-2',
        nameUa: 'Золотий',
        nameEn: 'Golden',
        tonePale: '#FFFAF0',
        toneMedium: '#FFD700',
        toneDeep: '#DAA520',
        colorHex: '#FFD700',
        sortNumber: 2,
      },
      {
        id: '2-3',
        nameUa: 'Бурштиновий',
        nameEn: 'Amber',
        tonePale: '#FFE4B5',
        toneMedium: '#FFA500',
        toneDeep: '#FF8C00',
        colorHex: '#FFA500',
        sortNumber: 3,
      },
    ],
  },
  {
    id: '3',
    nameUa: 'Рожевий',
    nameEn: 'Rosé',
    colorHex: '#FFB6C1',
    shades: [
      {
        id: '3-1',
        nameUa: 'Світло-рожевий',
        nameEn: 'Light Pink',
        tonePale: '#FFF0F5',
        toneMedium: '#FFB6C1',
        toneDeep: '#FF69B4',
        colorHex: '#FFB6C1',
        sortNumber: 1,
      },
      {
        id: '3-2',
        nameUa: 'Лососевий',
        nameEn: 'Salmon',
        tonePale: '#FFE4E1',
        toneMedium: '#FA8072',
        toneDeep: '#E9967A',
        colorHex: '#FA8072',
        sortNumber: 2,
      },
      {
        id: '3-3',
        nameUa: 'Кораловий',
        nameEn: 'Coral',
        tonePale: '#FF7F50',
        toneMedium: '#FF6347',
        toneDeep: '#FF4500',
        colorHex: '#FF6347',
        sortNumber: 3,
      },
    ],
  },
  {
    id: '4',
    nameUa: 'Оранжевий',
    nameEn: 'Orange',
    colorHex: '#FFA500',
    shades: [
      {
        id: '4-1',
        nameUa: 'Персиковий',
        nameEn: 'Peach',
        tonePale: '#FFDAB9',
        toneMedium: '#FFA07A',
        toneDeep: '#CD853F',
        colorHex: '#FFA07A',
        sortNumber: 1,
      },
      {
        id: '4-2',
        nameUa: 'Мандариновий',
        nameEn: 'Tangerine',
        tonePale: '#FFE5B4',
        toneMedium: '#FFA500',
        toneDeep: '#FF8C00',
        colorHex: '#FFA500',
        sortNumber: 2,
      },
    ],
  },
]
