// import { WineType } from './types/wine-type'

// export const mockWineTypes: WineType[] = [
//   {
//     id: 'red',
//     label: 'Красное вино',
//     labelEn: 'Red Wine',
//     color: "#8b",
//     aromas: ['berry', 'spicy', 'woody'],
//     flavorNotes: ['fruity', 'earthy', 'oaky'],
//     flavorCharacteristics: ['tannic', 'full-bodied', 'dry'],
//   },
//   {
//     id: 'white',
//     label: 'Белое вино',
//     labelEn: 'White Wine',
//     color: ,
//     aromas: ['citrus', 'tropical', 'floral'],
//     flavorNotes: ['mineral', 'herbal', 'fruity'],
//     flavorCharacteristics: ['acidic', 'dry', 'light'],
//   },
//   {
//     id: 'rose',
//     label: 'Розовое вино',
//     labelEn: 'Rosé Wine',
//     color: ['salmon', 'pink', 'peach'],
//     aromas: ['red_fruits', 'floral_rose', 'herbal'],
//     flavorNotes: ['fruity', 'fresh', 'citrus'],
//     flavorCharacteristics: ['light', 'dry', 'refreshing'],
//   },
//   {
//     id: 'sparkling',
//     label: 'Игристое вино',
//     labelEn: 'Sparkling Wine',
//     colors: ['champagne', 'blush'],
//     aromas: ['bready', 'citrus_sparkling', 'mineral_sparkling'],
//     flavorNotes: ['toasty', 'yeasty', 'citrus'],
//     flavorCharacteristics: ['bubbly', 'crisp', 'dry'],
//   },
//   {
//     id: 'dessert',
//     label: 'Десертное вино',
//     labelEn: 'Dessert Wine',
//     colors: ['amber', 'honey', 'caramel'],
//     aromas: ['dried_fruits', 'honey_aroma', 'spicy_dessert'],
//     flavorNotes: ['sweet', 'rich', 'complex'],
//     flavorCharacteristics: ['sweet', 'full-bodied', 'luscious'],
//   },
// ]

export const mockColors = [
  { id: 'ruby', label: 'Рубиновый' },
  { id: 'garnet', label: 'Гранатовый' },
  { id: 'purple', label: 'Пурпурный' },
  { id: 'straw', label: 'Соломенный' },
  { id: 'golden', label: 'Золотистый' },
  { id: 'lemon', label: 'Лимонный' },
  { id: 'salmon', label: 'Лососевый' },
  { id: 'pink', label: 'Розовый' },
  { id: 'peach', label: 'Персиковый' },
  { id: 'champagne', label: 'Шампанское' },
  { id: 'blush', label: 'Розовое игристое' },
  { id: 'amber', label: 'Янтарный' },
  { id: 'honey', label: 'Медовый' },
  { id: 'caramel', label: 'Карамельный' },
]

export const mockAromas = [
  { id: 'berry', label: 'Ягодный' },
  { id: 'spicy', label: 'Пряный' },
  { id: 'woody', label: 'Древесный' },
  { id: 'citrus', label: 'Цитрусовый' },
  { id: 'tropical', label: 'Тропический' },
  { id: 'floral', label: 'Цветочный' },
  { id: 'red_fruits', label: 'Красные фрукты' },
  { id: 'floral_rose', label: 'Цветочный (розовое)' },
  { id: 'herbal', label: 'Травяной' },
  { id: 'bready', label: 'Хлебный' },
  { id: 'citrus_sparkling', label: 'Цитрусовый (игристое)' },
  { id: 'mineral_sparkling', label: 'Минеральный (игристое)' },
  { id: 'dried_fruits', label: 'Сухофрукты' },
  { id: 'honey_aroma', label: 'Медовый' },
  { id: 'spicy_dessert', label: 'Пряный (десертное)' },
]

export const mockFlavorNotes = [
  { id: 'fruity', label: 'Фруктовый' },
  { id: 'earthy', label: 'Землистый' },
  { id: 'oaky', label: 'Дубовый' },
  { id: 'mineral', label: 'Минеральный' },
  { id: 'herbal', label: 'Травяной' },
  { id: 'fresh', label: 'Свежий' },
  { id: 'citrus', label: 'Цитрусовый' },
  { id: 'toasty', label: 'Поджаренный' },
  { id: 'yeasty', label: 'Дрожжевой' },
  { id: 'sweet', label: 'Сладкий' },
  { id: 'rich', label: 'Богатый' },
  { id: 'complex', label: 'Сложный' },
]

export const mockFlavorCharacteristics = [
  { id: 'tannic', label: 'Танинный' },
  { id: 'full-bodied', label: 'Полнотелый' },
  { id: 'dry', label: 'Сухой' },
  { id: 'acidic', label: 'Кислый' },
  { id: 'light', label: 'Легкий' },
  { id: 'refreshing', label: 'Освежающий' },
  { id: 'bubbly', label: 'Игристость' },
  { id: 'crisp', label: 'Хрустящий' },
  { id: 'sweet', label: 'Сладкий' },
  { id: 'luscious', label: 'Сочный' },
]
