import { WineType } from '@/modules/wine/create/wine-types/entities/types/wine-type'
import { IWines, WineImage, WinesResponse, WineFilters } from './types/types'

// Моковые типы вин с полем colors
const mockWineTypes: WineType[] = [
  {
    id: 'red',
    nameUa: 'Красное вино',
    nameEn: 'Red Wine',
    colors: [
      {
        id: 'red-1',
        nameUa: 'Темно-красный',
        nameEn: 'Dark Red',
        colorHex: '#8B0000',
      },
      {
        id: 'red-2',
        nameUa: 'Коричнево-красный',
        nameEn: 'Brown Red',
        colorHex: '#A52A2A',
      },
      {
        id: 'red-3',
        nameUa: 'Бордовый',
        nameEn: 'Burgundy',
        colorHex: '#800000',
      },
      {
        id: 'red-4',
        nameUa: 'Глубокий красный',
        nameEn: 'Deep Red',
        colorHex: '#5E1914',
      },
      {
        id: 'red-5',
        nameUa: 'Рубиновый',
        nameEn: 'Ruby',
        colorHex: '#722F37',
      },
    ],
  },
  {
    id: 'white',
    nameUa: 'Белое вино',
    nameEn: 'White Wine',
    colors: [
      {
        id: 'white-1',
        nameUa: 'Светло-соломенный',
        nameEn: 'Light Straw',
        colorHex: '#F5F5DC',
      },
      {
        id: 'white-2',
        nameUa: 'Золотистый',
        nameEn: 'Golden',
        colorHex: '#FFF8DC',
      },
      {
        id: 'white-3',
        nameUa: 'Бледно-желтый',
        nameEn: 'Pale Yellow',
        colorHex: '#FFEBCD',
      },
      {
        id: 'white-4',
        nameUa: 'Лимонный',
        nameEn: 'Lemon',
        colorHex: '#F0E68C',
      },
      {
        id: 'white-5',
        nameUa: 'Янтарный',
        nameEn: 'Amber',
        colorHex: '#EEE8AA',
      },
    ],
  },
  {
    id: 'dessert',
    nameUa: 'Десертное вино',
    nameEn: 'Dessert Wine',
    colors: [
      {
        id: 'dessert-1',
        nameUa: 'Розово-золотой',
        nameEn: 'Pink Gold',
        colorHex: '#e5bcbc',
      },
      {
        id: 'dessert-2',
        nameUa: 'Медовый',
        nameEn: 'Honey',
        colorHex: '#d8a8a8',
      },
      {
        id: 'dessert-3',
        nameUa: 'Персиковый',
        nameEn: 'Peach',
        colorHex: '#f0d9d9',
      },
      {
        id: 'dessert-4',
        nameUa: 'Карамельный',
        nameEn: 'Caramel',
        colorHex: '#d4a5a5',
      },
      {
        id: 'dessert-5',
        nameUa: 'Кремовый',
        nameEn: 'Cream',
        colorHex: '#ebc4c4',
      },
    ],
  },
  {
    id: 'sparkling',
    nameUa: 'Игристое вино',
    nameEn: 'Sparkling Wine',
    colors: [
      {
        id: 'sparkling-1',
        nameUa: 'Бледно-зеленый',
        nameEn: 'Pale Green',
        colorHex: '#f3f4e2',
      },
      {
        id: 'sparkling-2',
        nameUa: 'Серебристый',
        nameEn: 'Silver',
        colorHex: '#e8e9d7',
      },
      {
        id: 'sparkling-3',
        nameUa: 'Жемчужный',
        nameEn: 'Pearl',
        colorHex: '#f8f9e6',
      },
      {
        id: 'sparkling-4',
        nameUa: 'Прозрачно-золотой',
        nameEn: 'Clear Gold',
        colorHex: '#dde0c5',
      },
      {
        id: 'sparkling-5',
        nameUa: 'Кристальный',
        nameEn: 'Crystal',
        colorHex: '#f0f2d8',
      },
    ],
  },
]

const mockWineImages: WineImage[] = [
  {
    id: 'img-1',
    url: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=500&h=500&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=200&h=200&fit=crop',
    alt: 'Бутылка Château Margaux 2015',
    order: 1,
    fileSize: 1024000,
    mimeType: 'image/jpeg',
  },
  {
    id: 'img-2',
    url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&h=500&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=200&h=200&fit=crop',
    alt: 'Этикетка вина',
    order: 2,
    fileSize: 890000,
    mimeType: 'image/jpeg',
  },
  {
    id: 'img-3',
    url: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=500&h=500&fit=crop',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=200&h=200&fit=crop',
    alt: 'Виноградники региона',
    order: 3,
    fileSize: 1200000,
    mimeType: 'image/jpeg',
  },
]

export const mockWines: IWines[] = [
  {
    id: '1',
    displayName: 'Château Margaux 2015',
    producerTitle: 'Château Margaux',
    producerName: 'Château Margaux Estate',
    wine: 'Margaux Grand Cru',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Médoc',
    site: 'Margaux Appellation',
    type: mockWineTypes[0],
    subType: 'Grand Cru Classé',
    designation: 'AOC Margaux',
    classification: 'Premier Grand Cru Classé',
    vintageConfig: 2015,
    firstVintage: 1900,
    finalVintage: 2020,
    reference: 'MARGAUX-2015-001',
    description: "Вино з елегантним ароматом чорної смородини, фіалок та прянощів. М'який та багатий смак з довгим післясмаком.",
    images: [mockWineImages[0], mockWineImages[1], mockWineImages[2]],
    isConfirmed: false,
  },
  {
    id: '2',
    displayName: 'Domaine de la Romanée-Conti 2018',
    producerTitle: 'Domaine de la Romanée-Conti',
    producerName: 'DRC Estate',
    wine: 'Romanée-Conti Grand Cru',
    grapeVariety: 'Pinot Noir',
    country: 'France',
    region: 'Burgundy',
    subRegion: 'Côte de Nuits',
    site: 'Romanée-Conti Vineyard',
    type: mockWineTypes[0],
    subType: 'Grand Cru',
    designation: 'AOC Romanée-Conti',
    classification: 'Grand Cru',
    vintageConfig: 2018,
    firstVintage: 1945,
    finalVintage: 2020,
    reference: 'DRC-2018-001',
    description: 'Найвишуканіше бургундське вино з неймовірною складністю та довгим післясмаком.',
    images: [],
    isConfirmed: true,
  },
  {
    id: '3',
    displayName: 'Sassicaia 2016',
    producerTitle: 'Tenuta San Guido',
    producerName: 'San Guido Estate',
    wine: 'Sassicaia Bolgheri',
    grapeVariety: 'Cabernet Sauvignon, Cabernet Franc',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    site: 'Sassicaia Vineyard',
    type: mockWineTypes[0],
    subType: 'Super Tuscan',
    designation: 'DOC Bolgheri Sassicaia',
    classification: 'Iconic Wine',
    vintageConfig: 2016,
    firstVintage: 1968,
    finalVintage: 2020,
    reference: 'SASS-2016-001',
    description: 'Перше "супер тосканське" вино, що поєднує французькі сорти винограду з італійським терруаром.',
    images: [],
    isConfirmed: false,
  },
  {
    id: '4',
    displayName: 'Cloudy Bay Sauvignon Blanc 2022',
    producerTitle: 'Cloudy Bay Vineyards',
    producerName: 'Cloudy Bay',
    wine: 'Sauvignon Blanc',
    grapeVariety: 'Sauvignon Blanc',
    country: 'New Zealand',
    region: 'Marlborough',
    subRegion: 'Wairau Valley',
    site: 'Cloudy Bay Vineyard',
    type: mockWineTypes[1],
    subType: 'Single Vineyard',
    designation: 'Marlborough Sauvignon Blanc',
    classification: 'Premium',
    vintageConfig: 2022,
    firstVintage: 1985,
    finalVintage: 2023,
    reference: 'CB-SB-2022-001',
    description: 'Свіже вино з яскравими нотами passion fruit, аґрусу та тропічних фруктів.',
    images: [],
    isConfirmed: true,
  },
  {
    id: '5',
    displayName: 'Vega Sicilia Unico 2010',
    producerTitle: 'Bodegas Vega Sicilia',
    producerName: 'Vega Sicilia',
    wine: 'Unico Reserva',
    grapeVariety: 'Tinto Fino, Cabernet Sauvignon, Merlot',
    country: 'Spain',
    region: 'Ribera del Duero',
    subRegion: 'Valbuena',
    site: 'Vega Sicilia Estate',
    type: mockWineTypes[0],
    subType: 'Gran Reserva',
    designation: 'DO Ribera del Duero',
    classification: 'Gran Reserva',
    vintageConfig: 2010,
    firstVintage: 1915,
    finalVintage: 2018,
    reference: 'VS-UNICO-2010-001',
    description: 'Легендарне іспанське вино з великим потенціалом витримки, багате та комплексне.',
    images: [],
    isConfirmed: false,
  },
  {
    id: '6',
    displayName: 'Opus One 2017',
    producerTitle: 'Opus One Winery',
    producerName: 'Opus One',
    wine: 'Opus One',
    grapeVariety: 'Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec',
    country: 'USA',
    region: 'California',
    subRegion: 'Napa Valley',
    site: 'Oakville District',
    type: mockWineTypes[0],
    subType: 'Bordeaux Blend',
    designation: 'Napa Valley Red Wine',
    classification: 'Iconic',
    vintageConfig: 2017,
    firstVintage: 1979,
    finalVintage: 2020,
    reference: 'OPUS-2017-001',
    description: 'Результат співпраці барона Філіппа де Ротшильда та Роберта Мондаві. Елегантне та потужне вино.',
    images: [],
    isConfirmed: false,
  },
  {
    id: '7',
    displayName: "Château d'Yquem 2015",
    producerTitle: "Château d'Yquem",
    producerName: 'Yquem Estate',
    wine: 'Sauternes',
    grapeVariety: 'Sémillon, Sauvignon Blanc',
    country: 'France',
    region: 'Bordeaux',
    subRegion: 'Sauternes',
    site: 'Yquem Vineyard',
    type: mockWineTypes[2],
    subType: 'Liquoreux',
    designation: 'AOC Sauternes',
    classification: 'Premier Cru Supérieur',
    vintageConfig: 2015,
    firstVintage: 1785,
    finalVintage: 2020,
    reference: 'YQUEM-2015-001',
    description: 'Найвідоміше солодке вино у світі з нотами меду, абрикосу та карамелі.',
    images: [],
    isConfirmed: false,
  },
  {
    id: '8',
    displayName: 'Penfolds Grange 2018',
    producerTitle: 'Penfolds',
    producerName: 'Penfolds Winery',
    wine: 'Grange Shiraz',
    grapeVariety: 'Shiraz',
    country: 'Australia',
    region: 'South Australia',
    subRegion: 'Barossa Valley',
    site: 'Multiple Vineyards',
    type: mockWineTypes[0],
    subType: 'Shiraz',
    designation: 'South Australian Shiraz',
    classification: 'Iconic',
    vintageConfig: 2018,
    firstVintage: 1951,
    finalVintage: 2020,
    reference: 'PEN-GRANGE-2018-001',
    description: 'Найвідоміше австралійське вино, потужне та багате з нотами темних фруктів та спецій.',
    images: [],
    isConfirmed: true,
  },
  {
    id: '9',
    displayName: 'Masseto 2019',
    producerTitle: "Tenuta dell'Ornellaia",
    producerName: 'Ornellaia Estate',
    wine: 'Masseto',
    grapeVariety: 'Merlot',
    country: 'Italy',
    region: 'Tuscany',
    subRegion: 'Bolgheri',
    site: 'Masseto Vineyard',
    type: mockWineTypes[0],
    subType: 'Merlot',
    designation: 'Bolgheri DOC',
    classification: 'Iconic',
    vintageConfig: 2019,
    firstVintage: 1986,
    finalVintage: 2020,
    reference: 'MASSETO-2019-001',
    description: '100% Merlot з унікального терруару, часто порівнюють з Pétrus.',
    images: [],
    isConfirmed: true,
  },
  {
    id: '10',
    displayName: 'Krug Grande Cuvée 169ème Édition',
    producerTitle: 'Krug',
    producerName: 'Krug Champagne House',
    wine: 'Grande Cuvée',
    grapeVariety: 'Pinot Noir, Chardonnay, Pinot Meunier',
    country: 'France',
    region: 'Champagne',
    subRegion: 'Reims',
    site: 'Multiple Crus',
    type: mockWineTypes[3],
    subType: 'Prestige Cuvée',
    designation: 'AOC Champagne',
    classification: 'Prestige Cuvée',
    vintageConfig: 2020,
    firstVintage: 1843,
    finalVintage: 2020,
    reference: 'KRUG-GC-169-001',
    description: 'Легендарне шампанське з неймовірною складністю та багаторічним потенціалом.',
    images: [],
    isConfirmed: true,
  },
]

// Мок для ответа с пагинацией
export const mockWinesResponse: WinesResponse = {
  rows: mockWines,
  totalCount: mockWines.length,
}

// Мок для фильтров
export const mockWineFilters: WineFilters = {
  limit: 10,
  offset: 0,
  search: '',
}

// Мок для подтверждения вина
export const mockConfirmWineParams = {
  id: '1',
  isConfirmed: true,
}

// Мок для обновления вина
export const mockUpdateWineParams = {
  id: '1',
  data: mockWines[0],
}

// Мок для импорта вина
export const mockImportWineParams = {
  file: new File([''], 'wines.csv', { type: 'text/csv' }),
}

export { mockWineTypes, mockWineImages }
